### ISSUE TITLE
Roadmap - January 22 2024

### ISSUE THREAD

**Issue by jyu283** [jyu283/tritongrader#15]
- [x] Make package self-sustaining. (No need to make manual modifications to the library code for every PA.)
- [x] Valgrind interface somehow
- [x] Extra file check
- [x] #8
- [ ] Improve build rule configuration workflow. Remove ugly `arm` flag.
- [x] #6
- [ ] Compile error
- [x] Improve rubric output workflow. (_E.g._, create `GradescopeRubric` class to handle gradescope rubric format)
- [x] Better observability and logging
- [x] Better test suite/test case configuration interface.
